name: Main status

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  lint-test-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: vs Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Test
        run: |
          go test -v ./... -covermode=count -coverprofile=coverage.out

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          verbose: true

      - name: Build
        run: go build -v ./...

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build And Push Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/dnc:latest